/* Titles */
TXT_TITLE_LAUNCHER      Amber Island Launcher
TXT_TITLE_GAMENOTFOUND  Game not found!

/* Buttons */
TXT_BTN_PLAY            Play
TXT_BTN_CONFIGURE       Configure
TXT_BTN_BROWSE          Browse
TXT_BTN_SUBMIT          Submit

/* Texts */
TXT_GREETINGS           Greetings adventurer, before you can play Amber Island, you have to configure the game.\nMake sure you have Might and Magic 7 installed on your PC.
TXT_GAMENOTFOUND        Launcher couldn\'t locate the Might & Magic 7 installation. Please select the game executable (mm7.exe)
