/* Titles */
TXT_TITLE_DEBUG         Debug Console
TXT_TITLE_LAUNCHER      Amber Island Launcher
TXT_TITLE_GAMENOTFOUND  Game not found!
TXT_TITLE_MESSAGE       Message
TXT_TITLE_QUESTION      Question
TXT_TITLE_TWEAKER       Tweaker
TXT_TITLE_LOCALISATION  Localisation
TXT_TITLE_OPTIONS       Options

/* Buttons */
TXT_BTN_YES             Yes
TXT_BTN_NO              No
TXT_BTN_PLAY            Play
TXT_BTN_CONFIGURE       Configure
TXT_BTN_BROWSE          Browse
TXT_BTN_SUBMIT          Submit
TXT_BTN_ACCEPT          Accept
TXT_BTN_CANCEL          Cancel
TXT_BTN_OK              OK
TXT_BTN_CONTINUE        Continue
TXT_BTN_NEXT            Next
TXT_BTN_PREVIOUS        Previous

/* Localisation */
TXT_LOC_CORE            Main Game
TXT_LOC_MOD             Mod
TXT_LOC_AUDIO           Audio
TXT_LOC_MEDIA           Media
TXT_LOC_ENGLISH         English
TXT_LOC_GERMAN          German
TXT_LOC_SPANISH         Spanish
TXT_LOC_FRENCH          French
TXT_LOC_POLISH          Polish
TXT_LOC_CZECH           Czech
TXT_LOC_HUNGARIAN       Hungarian
TXT_LOC_UKRAINIAN       Ukrainian
TXT_LOC_RUSSIAN         Russian

/* Texts */
TXT_NULL                Null
TXT_GREETINGS           Greetings adventurer, before you can play Amber Island, you have to configure the game.\nMake sure you have Might and Magic 7 installed on your PC.
TXT_CONFIGSUCCESS       Setup complete! You can now play the Amber Island mod. Press Next to close autoconfig and jump in.
TXT_GAMENOTFOUND        Launcher couldn't locate the Might and Magic 7 installation. Please locate the game executable (mm7.exe)
TXT_LOCALISATION        Select languages for core game texts, voiceovers, and mod texts. Customize each option individually to personalize your gameplay experience.
